package controller;

public enum Events {

    ACTIVAR_CALENDARIO,ACTIVAR_CALENDARIO_END,OK_OPTION, OK_OPTION_END, SEARCH_PREALERTA, SHOW_ALL_PREALERTAS, SHOW_UPDATE_PREALERTA, UPDATE_PREALERTA,
    SHOW_CREATE_PREALERTA, SHOW_DELETE_PREALERTA, ACCEPT_DELETE, ACCEPT_CREATE_PREALERTA, SHOW_CREATE_EQUIPMENT_TYPE, CREATE_EQUIPMENT_TYPE, SHOW_UPDATE_EQUIPMENT_TYPE,
    UPDATE_EQUIPMENT_TYPE, SHOW_DELETE_EQUIPMENT_TYPE, DELETE_EQUIPMENT_TYPE, SEARCH_EQUIPMENT_PREALERTA, ADD_EQUIPMENT_TO_PREALERTA, SHOW_ADD_EQUIPMENT_TO_PREALERTA,
    INSERT_DATA_EXCEL, SEARCH_EQUIPMENT_PREALERTA_COLLECTION, COLLECTION_EQUIPMENT, DELETE_EQUIPMENT, ACCEPT_DELETE_EQUIPMENT

}
